name: shelfie_app
description: Real-time book and product finder using camera OCR
publish_to: 'none'
version: 1.0.1+5 # 왼쪽은 버전, 오른쪽은 빌드번호

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  google_mlkit_text_recognition: ^0.14.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.3
  permission_handler: ^11.3.1
  vibration: ^2.0.0
  in_app_update: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#1B8BD1"
  adaptive_icon_foreground: "assets/app_icon.png"
